### ISSUE TITLE
登录时报错

### ISSUE THREAD

**Issue by decker502** [UlricQin/uic#1]
按照文档部署后，登录时报错，请支援，谢谢

```
java.lang.reflect.InvocationTargetException
```

下面是tomcat的日志输出

```
>>> java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.jfinal.core.ActionInvocation.invoke(ActionInvocation.java:61)
        at com.ulricqin.uic.interceptor.GlobalInterceptor.intercept(GlobalInterceptor.java:11)
        at com.jfinal.core.ActionInvocation.invoke(ActionInvocation.java:51)
        at com.jfinal.core.ActionHandler.handle(ActionHandler.java:77)
        at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:72)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:615)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
        at org.apache.coyote.http11.Http11NioProcessor.process(Http11NioProcessor.java:891)
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:750)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:2282)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at com.jfinal.core.ActionInvocation.invoke(ActionInvocation.java:55)
        ... 19 more
Caused by: java.lang.NoSuchMethodError: javax.servlet.http.Cookie.setHttpOnly(Z)V
        at com.ulricqin.uic.controller.AuthController.genCookie(AuthController.java:237)
        at com.ulricqin.uic.controller.AuthController.registerPost(AuthController.java:224)
        at com.ulricqin.uic.controller.AuthController.register(AuthController.java:181)
        ... 24 more
```

**Comment by UlricQin** [comment]
关键是这句话：java.lang.NoSuchMethodError: javax.servlet.http.Cookie.setHttpOnly
看来是版本不能太低，使用tomcat7吧，我的JDK也是7

**Comment by UlricQin** [comment]
https://github.com/open-falcon/doc/wiki/Install-Judge-components 这里有一个uic打好的包，只要安装JDK7，然后把包下载下来解压缩，启动即可：

```
cd bin && ./startup.sh
```

**Comment by decker502** [comment]
果然是版本问题，现在解决了，多谢
